### ISSUE TITLE
When one tab overlaps another and is being dragged, one behind it is being moved as well

### ISSUE THREAD

**Issue by JDuchniewicz** [PolyEngineTeam/PolyDock#29]
As in the title, see attached video.
![issue](https://user-images.githubusercontent.com/18423461/78603879-29630880-7859-11ea-94f4-10169d804b84.gif)

**Comment by PiotrSquaresMoscicki** [comment]
Will be resolved after https://github.com/PolyEngineTeam/PolyDock/issues/13 is done
